version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
